index_category = {0: 'Thoi_trang_nam',
                 1: 'Thoi_trang_nu',
                 2: 'Dien_thoai_Phu_kien',
                 3: 'Me_be',
                 4: 'Thiet_bi_DT',
                 5: 'Nha_cua_va_doi_song',
                 6: 'May_tinh_Laptop',
                 7: 'Suc_khoe_Sac_dep',
                 8: 'May_anh_quay_phim',
                 9: 'Giay_dep_nu',
                 10: 'Dong_ho',
                 11: 'Tui_vi',
                 12: 'Giay_dep_nam',
                 13: 'Phu_kien_thoi_trang',
                 14: 'TB_dien_gia_dung',
                 15: 'Bach_hoa_online',
                 16: 'The_thao_du_lich',
                 17: 'Voucher_dich_vu',
                 18: 'Oto_xe_may_xe_dap',
                 19: 'Nha_sach_online',
                 20: 'Do_choi',
                 21: 'Giat_giu_cham_soc_nha_cua',
                 22: 'Cham_soc_thu_cung',
                 23: 'Thoi_trang_tre_em',
                 24: 'San_pham_khac'}

